// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "input": string;
      "apiProvider": string;
      "customApiUrl": string;
      "customApiHeaders": string;
      "customApiTransPath": string;
      "customApiDefPath": string;
      "customApiPosPath": string;
      "customApiPhonePath": string;
      "uiLanguage": string;
      "exportFormat": string;
      "exportScope": string;
    };
  }
}
