pref("enable", true);
pref("input", "This is input");
pref("apiProvider", "youdao");
pref("customApiUrl", "");
pref("customApiHeaders", "{}");
pref("customApiTransPath", "");
pref("customApiDefPath", "");
pref("customApiPosPath", "");
pref("customApiPhonePath", "");
pref("uiLanguage", "zh-CN");
pref("quickAddShortcut", "alt+a");
pref("translationCachePath", "");
pref("exportFormat", "csv");
pref("exportScope", "all");
